import '/public/assets/css/bootstrap.min.css'    
import "/public/assets/css/all.min.css"
import "/public/assets/css/animate.css"
import "/public/assets/css/magnific-popup.css"
import "/public/assets/css/meanmenu.css"
import "/public/assets/css/swiper-bundle.min.css"
import "/public/assets/css/nice-select.css"
import "/public/assets/css/main.css"
import { Kumbh_Sans } from 'next/font/google'
import Footer1 from "@/components/layout/footer/Footer1"
import Head from "next/head"
import TranslationsProvider from '@/components/TranslationsProvider'
import initTranslations from '../i18n'
import HomeTracking from '@/components/elements/HomeTracking'

const kumbh = Kumbh_Sans({
    weight: ['300', '400', '500', '600', '700','800','900'],
    subsets: ['latin'],
    display: 'swap',
})

export const metadata = {
  title: 'Mavistay Agency ',
  description: 'Generated by create next app',
}
const i18nNamespaces=['home','navbar']
export default async function RootLayout({ children ,params:{locale}}) {
  const {resources} = await initTranslations(locale,i18nNamespaces)
  return (
    <html lang={'ar'} dir='rtl'>
      <Head>
      <link href="../../public/assets/img/Icons/mavistay-Logo.png" rel="icon" type="image/x-icon"></link>
        <title>{metadata.title}</title>
        <meta name="description" content="Mavistay Toursim agency" />
        <meta name="keywords" content="nextjs, seo, react" />
      </Head>
      <body className={`${kumbh.className}`} dir={locale}>
        <TranslationsProvider locale={locale} resources={resources} namespaces={i18nNamespaces}>
        {children}
        </TranslationsProvider>
        <Footer1/>
        </body>
    </html>
  )
}
